### ISSUE TITLE
Elm Track - Robot Simulator - All tests passed but not able to complete the exercise

### ISSUE THREAD

**Issue by 552020** [exercism/elm-test-runner#33]
I tried many times also to submit the solution through the CLI: all tests have been passed but it says 'failed' nonetheless.

![image](https://user-images.githubusercontent.com/60273337/159157571-458f2e95-ad5a-4c56-ba83-f1513d9aae0c.png)

**Comment by ErikSchierboom** [comment]
I've tested this locally, and the problem seems to be in the produced `results.json` file:

```json
{
  "version": 3,
  "status": "fail",
  "tests": [
    {
      "name": "coordinates",
      "task_id": null,
      "status": "pass",
      "message": null,
      "output": null,
      "test_code": "Expect.equal {x = 0, y = 0} defaultRobot.coordinates"
    },
    {
      "name": "bearing",
      "task_id": null,
      "status": "pass",
      "message": null,
      "output": null,
      "test_code": "Expect.equal North defaultRobot.bearing"
    },
    {
      "name": "coordinates",
      "task_id": null,
      "status": "pass",
      "message": null,
      "output": null,
      "test_code": "Robot anyBearing {x = -1, y = 1} |> ..coordinates\n |> Expect.equal {x = -1, y = 1}"
    },
    {
      "name": "bearing",
      "task_id": null,
      "status": "pass",
      "message": null,
      "output": null,
      "test_code": "Robot South anyCoordinates |> ..bearing\n |> Expect.equal South"
    },
    {
      "name": "step 0",
      "task_id": null,
      "status": "pass",
      "message": null,
      "output": null,
      "test_code": "Robot North {x = 0, y = 0} |> advance |> ..coordinates\n |> Expect.equal {x = 0, y = 1}"
    },
    {
      "name": "step 1",
      "task_id": null,
      "status": "pass",
      "message": null,
      "output": null,
      "test_code": "Robot North {x = 0, y = 0} |> advance |> ..bearing\n |> Expect.equal North"
    },
    {
      "name": "step 2",
      "task_id": null,
      "status": "pass",
      "message": null,
      "output": null,
      "test_code": "Robot East {x = 0, y = 0} |> advance |> ..coordinates\n |> Expect.equal {x = 1, y = 0}"
    },
    {
      "name": "step 3",
      "task_id": null,
      "status": "pass",
      "message": null,
      "output": null,
      "test_code": "Robot East {x = 0, y = 0} |> advance |> ..bearing\n |> Expect.equal East"
    },
    {
      "name": "step 0",
      "task_id": null,
      "status": "pass",
      "message": null,
      "output": null,
      "test_code": "Robot South {x = 0, y = 0} |> advance |> ..coordinates\n |> Expect.equal {x = 0, y = -1}"
    },
    {
      "name": "step 1",
      "task_id": null,
      "status": "pass",
      "message": null,
      "output": null,
      "test_code": "Robot South {x = 0, y = 0} |> advance |> ..bearing\n |> Expect.equal South"
    },
    {
      "name": "step 2",
      "task_id": null,
      "status": "pass",
      "message": null,
      "output": null,
      "test_code": "Robot West {x = 0, y = 0} |> advance |> ..coordinates\n |> Expect.equal {x = -1, y = 0}"
    },
    {
      "name": "step 3",
      "task_id": null,
      "status": "pass",
      "message": null,
      "output": null,
      "test_code": "Robot West {x = 0, y = 0} |> advance |> ..bearing\n |> Expect.equal West"
    },
    {
      "name": "coordinates",
      "task_id": null,
      "status": "pass",
      "message": null,
      "output": null,
      "test_code": "Robot North {x = 0, y = 0} |> simulate \"LAAARALA\" |> ..coordinates\n |> Expect.equal {x = -4, y = 1}"
    },
    {
      "name": "bearing",
      "task_id": null,
      "status": "pass",
      "message": null,
      "output": null,
      "test_code": "Robot North {x = 0, y = 0} |> simulate \"LAAARALA\" |> ..bearing\n |> Expect.equal West"
    },
    {
      "name": "coordinates",
      "task_id": null,
      "status": "pass",
      "message": null,
      "output": null,
      "test_code": "Robot East {x = 2, y = -7} |> simulate \"RRAAAAALA\" |> ..coordinates\n |> Expect.equal {x = -3, y = -8}"
    },
    {
      "name": "bearing",
      "task_id": null,
      "status": "pass",
      "message": null,
      "output": null,
      "test_code": "Robot East {x = 2, y = -7} |> simulate \"RRAAAAALA\" |> ..bearing\n |> Expect.equal South"
    },
    {
      "name": "coordinates",
      "task_id": null,
      "status": "pass",
      "message": null,
      "output": null,
      "test_code": "Robot South {x = 8, y = 4} |> simulate \"LAAARRRALLLL\" |> ..coordinates\n |> Expect.equal {x = 11, y = 5}"
    },
    {
      "name": "bearing",
      "task_id": null,
      "status": "pass",
      "message": null,
      "output": null,
      "test_code": "Robot South {x = 8, y = 4} |> simulate \"LAAARRRALLLL\" |> ..bearing\n |> Expect.equal North"
    }
  ]
}
```

The `fail` status should be present if one or more tests have the `fail` status. In this case, there are no tests that have the `fail` status, so either the `fail` status is calculated incorrectly, or some tests are missing.

**Comment by ErikSchierboom** [comment]
CC @ceddlyburge @mpizenberg

**Comment by mpizenberg** [comment]
@552020 @ErikSchierboom thanks for the report. We are indeed aware of this bug. This is related to our test parser that extracts the test code for the test runner report. It has been fixed as seen in https://github.com/exercism/elm-test-runner/issues/29. This will be rolled out as soon as I take some time updating the test runner, which I suspect is next week.

**Comment by ErikSchierboom** [comment]
Excellent!

**Comment by mpizenberg** [comment]
Hum, my bad, the fix was done by removing the `let` expression in the robot simulator test. The support for `let` expression in the tests is not done yet as registered in that issue https://github.com/exercism/elm-test-runner/issues/30.

I'm reopening this issue then because It should be solved since the exercise was updated (https://github.com/exercism/elm/pull/463). Is it possible @552020 that you are still running the tests of the old version (previous to our fix), how could we check that @ErikSchierboom ?

**Comment by ErikSchierboom** [comment]
@mpizenberg I don't think it is fixed. I've upgraded the exercise to the latest version (which you can do on the website) and tested it in the online editor, and found the same issue.

**Comment by jiegillet** [comment]
I took a look, there is definitely a problem, and it's not exactly the same as before.
There are 26 tests in the exercise, but only 18 show up in `results.json` and the names are all messed up.

Basically, the test code extractor fails on the 8 tests in `describe "right"` and `describe "left"`, because of this line
```elm
|> List.indexedMap (\i e -> test ("step " ++ String.fromInt i) (\() -> e))
```
The code extractor cannot work with `test ("step " ++ String.fromInt i)` it can only deal with a single string literal (like `test "step 1"`). Changing the code extractor to deal with this would be very complex, and even if it did manage to extract the code, it would display `e`, which is fairly useless, so I think we should rewrite those tests instead.

**Comment by jiegillet** [comment]
@552020 the tests have been updated, please try again.

You should get some failing tests this time, because your `simulate` reverses the order of operations. Let me know if you need some mentoring once you pass the tests :)

**Comment by ceddlyburge** [comment]
Thanks for reporting / fixing this everyone, I've been away on holiday .
Should we update this issue to check that the test runner works with the test code do you think?
https://github.com/exercism/elm/issues/412

**Comment by 552020** [comment]
Thank you everyone for fixing this. @jiegillet I run the updated exercise with my old spaghetti code and it works as it is. I will open nonetheless a mentoring request, cause I struggled a lot with this one. 

Probably this is not the right place for this question and I should open another issue for it: sometimes, as a learner, you would need mentoring before you pass all the tests. Probably this is not possible cause you want to avoid too many mentoring requests but in certain cases, it would help to be mentored before you pass all the tests.  I'm stuck for example on the Pythagorean Triplets challenge. I solved it conceptually with a brute force approach based on recursion which is too expensive memory-wise and I get a stackoverflow on the test with the big numbers. I tried to refactor it but my alternative solutions give similar problems and now I'm trying to understand the maths behind the triplet and deliver a mathematical solution. I think that for cases like these, where the learner came up with a valid working solution with some flaws it would be meaningful to allow him to open a mentoring request. If you think that is issue/proposal is worth to be discussed I can open a separate issue.

**Comment by ErikSchierboom** [comment]
Thanks for fixing @jiegillet !

**Comment by 552020** [comment]
And by the way, what I wrote is not true. My spaghetti code solution throws 4 errors, so everything is fine. I forgot that I've copied the example solution in the editor.

**Comment by jiegillet** [comment]
@552020 I'm glad that your code fails now (lol). I will close the issue then.

Concerning receiving mentorship, there is trick: if you submit via the CLI you should be able to ask for it even if the tests fail, but your request is a common one, please check exercism/exercism to see if there is an issue open already.

Concerning pythagorean triples, my favorite way to solve the exercise very efficiently is via [this mathematical trick](https://en.wikipedia.org/wiki/Formulas_for_generating_Pythagorean_triples#Pythagorean_triples_by_use_of_matrices_and_linear_transformations), (there are also a bunch ways on that link).

**Comment by 552020** [comment]
@jiegillet Thank you for the trick suggestion. I found a forgotten open issue/suggestion about it: https://github.com/exercism/exercism/issues/6187
