### ISSUE TITLE
Update `elm-explorations/test`?

### ISSUE THREAD

**Issue by jiegillet** [exercism/elm-test-runner#42]
`elm-explorations/test` has received a major update, along with `elm-test` and `elm-test-rs`.
Should we update `elm-test-rs` here? If we do, we will need to update the dependency of every exercise `elm.json`.

This is not urgent, as students will not be writing tests, but it would be nice to keep our own tests up to date.

**Comment by mpizenberg** [comment]
If you want to do it go for it. There is probably nothing to change in the tests since we do not use fuzz testing in exercise tests. But a check that elm-test-rs did not break anything is still required.

**Comment by mpizenberg** [comment]
On remark, old versions of elm-test do not officially support elm-explorations/test v2, but in practice, I seem to remember that it sort of work (just that fuzz tables which is a new thing are not displayed, but that does not concerns us). So even with students who have not updated their elm-test, it should not cause issue when they call `elm-test` locally if they are on the command line and not online.
