### ISSUE TITLE
Problem when using `Debug.log`

### ISSUE THREAD

**Issue by mpizenberg** [exercism/elm-test-runner#5]
I just realized that using `Debug.log` inside the code will print to the junit `report.xml` file making it invalid and crashing the python script converting the junit report to exercism format. I can see two "solutions",
* (1) changing the python script to ignore all lines except the last one, that contain the xml. This however prevents students from seeing the output of debug logging.
* (2) ask @iHiD how they dealt with this in the ruby track ^^

**Comment by iHiD** [comment]
In Ruby, I provide a specific method `debug()` to use instead of the normal puts/print options. This captures the output and pops it in the correct place in the results.json. @ErikSchierboom captured the stdout and put it in the right place instead I believe.

**Comment by ErikSchierboom** [comment]
Actually, my test framework has a special method to capture output, which I then link up to the default console output methods. But I know other tracks just capture stdout.
