### ISSUE TITLE
Fail the run if a concept exercise is missing a task id

### ISSUE THREAD

**Issue by jiegillet** [exercism/elm-test-runner#50]
Tasks id are set by using `describe "1"` and the like in test files.
This is poorly documented and not obvious so the CI check should fail if any concept exercise test is missing its task id.

Identifying which exercise is a concept exercise is tricky though. Maintaining a specific list over here would be a maintaining burden, so maybe we need to identify it from the config file or something like that?

Alternatively, maybe we only need to run this in the CI over in `exercism/elm` when we check all the exercises?

**Comment by mpizenberg** [comment]
Shouldn't it possible to have tests are are relevant to multiple tasks? or just preliminary tests specifically made to check a few things and not relevant to any particular task?

**Comment by jiegillet** [comment]
I don't think we have any tests like that at the moment, and I don't think the web interface would handle those very well. I think it's best to require that each test be assigned to a task. We have total creative control over concept exercises anyway, we can duplicate tests if it's necessary (but I'm having a hard time imagining why we would want that).
